replicaCount: 2

image:
  repository: kartavyanirwel/ecommerce-auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8081

secretEnv:
  - DB_USER
  - DB_PASSWORD
  - JWT_SECRET

configEnv:
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_NAME: auth_db
  CORS_ALLOWED_ORIGINS: "https://your-frontend-domain.com"